Keybind()
  :with_keymap('<C-h>')
  :with_mode('n')
  :with_description('Navigate to the left window')
  :with_callback('<C-w>h')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-j>')
  :with_mode('n')
  :with_description('Navigate to the bottom window')
  :with_callback('<C-w>j')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-k>')
  :with_mode('n')
  :with_description('Navigate to the top window')
  :with_callback('<C-w>k')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-l>')
  :with_mode('n')
  :with_description('Navigate to the right window')
  :with_callback('<C-w>l')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-Up>')
  :with_mode('n')
  :with_description('Increase window height')
  :with_callback(function()
  vim.cmd([[ resize +2 ]])
end)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-Down>')
  :with_mode('n')
  :with_description('Decrease window height')
  :with_callback(function()
  vim.cmd([[ resize -2 ]])
end)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-Left>')
  :with_mode('n')
  :with_description('Decrease window width')
  :with_callback(function()
  vim.cmd([[ vertical resize -2 ]])
end)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<C-Right>')
  :with_mode('n')
  :with_description('Increase window width')
  :with_callback(function()
  vim.cmd([[ vertical resize +2 ]])
end)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<Tab>')
  :with_mode('n')
  :with_description('Navigate to the next buffer')
  :with_callback(vim.cmd.bnext)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<S-Tab>')
  :with_mode('n')
  :with_description('Navigate to the previous buffer')
  :with_callback(vim.cmd.bprevious)
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('p')
  :with_mode('v')
  :with_description('Paste over the visual selection')
  :with_callback('"_dP')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('<')
  :with_mode('v')
  :with_description('Shift left the visual selection')
  :with_callback('<gv')
  :non_remappable()
  :silent()
  :build()
Keybind()
  :with_keymap('>')
  :with_mode('v')
  :with_description('Shift right the visual selection')
  :with_callback('>gv')
  :non_remappable()
  :silent()
  :build()
