local icons = {}

local data = {
  kind = {
    Class = 'ﴯ',
    Color = '',
    Constant = '',
    Constructor = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '',
    Function = '',
    Interface = '',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '',
    Number = '',
    Operator = '',
    Package = '',
    Property = 'ﰠ',
    Reference = '',
    Snippet = '',
    Struct = '',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',
    TypeAlias = '',
    Parameter = '',
    StaticMethod = '',
    Macro = '',
  },
  type = {
    Array = '',
    Boolean = '',
    Null = 'ﳠ',
    Number = '',
    Object = '',
    String = '',
  },
  documents = {
    Default = '',
    File = '',
    Files = '',
    FileTree = 'פּ',
    Import = '',
    Symlink = '',
  },
  git = {
    Add = '',
    Branch = '',
    Diff = '',
    Git = '',
    Ignore = '',
    Mod = 'M',
    ModAlternative = '',
    Remove = '',
    Rename = '',
    Repo = '',
    Unmerged = 'שׂ',
    Untracked = 'ﲉ',
    Unstaged = '',
    Staged = '',
    Conflict = '',
  },
  ui = {
    ArrowClosed = '',
    ArrowOpen = '',
    BigCircle = '',
    BigUnfilledCircle = '',
    BookMark = '',
    Bug = '',
    Calendar = '',
    Check = '',
    ChevronRight = '',
    Circle = '',
    Close = '',
    CloseAlternative = '',
    CloudDownload = '',
    Comment = '',
    CodeAction = '',
    Dashboard = '',
    Emoji = '',
    EmptyFolder = '',
    EmptyFolderOpen = '',
    File = '',
    Fire = '',
    Folder = '',
    FolderOpen = '',
    Gear = '',
    History = '',
    Incoming = '',
    Indicator = '',
    Keyboard = '',
    Left = '',
    List = '',
    Square = '',
    SymlinkFolder = '',
    Lock = '',
    Modified = '✥',
    ModifiedAlternative = '',
    NewFile = '',
    Newspaper = '',
    Note = '',
    Outgoing = '',
    Package = '',
    Pencil = '',
    Perf = '',
    Play = '',
    Project = '',
    Right = '',
    RootFolderOpened = '',
    Search = '',
    Separator = '',
    DoubleSeparator = '',
    SignIn = '',
    SignOut = '',
    Sort = '',
    Spell = '暈',
    Symlink = '',
    Table = '',
    Telescope = '',
  },
  diagnostics = {
    Error = '',
    Warning = '',
    Information = '',
    Question = '',
    Hint = '',
    ErrorAlternative = '',
    WarningAlternative = '',
    InformationAlternative = '',
    QuestionAlternative = '',
    HintAlternative = '',
  },
  misc = {
    Campass = '',
    Code = '',
    EscapeST = '✺',
    Gavel = '',
    Glass = '',
    PyEnv = '',
    Squirrel = '',
    Tag = '',
    Tree = '',
    Watch = '',
    Lego = '',
    Vbar = '│',
    Add = '+',
    Added = '',
    Ghost = '',
    ManUp = '',
    Vim = '',
  },
  cmp = {
    Codeium = '',
    TabNine = '',
    Copilot = '',
    CopilotAlternative = '',
    LanguageServerProtocol = '',
    Lua = '',
    Path = '',
    Buffer = '',
    Spell = '暈',
    LuaSnip = '',
    Treesitter = '',
  },
  dap = {
    Breakpoint = '',
    BreakpointCondition = 'ﳁ',
    BreakpointRejected = '',
    LogPoint = '',
    Pause = '',
    Play = '',
    RunLast = '↻',
    StepBack = '',
    StepInto = '',
    StepOut = '',
    StepOver = '',
    Stopped = '',
    Terminate = 'ﱢ',
  },
}

---Gets a specific icon set by category.
---
---@param category 'kind' | 'type' | 'documents' | 'git' | 'ui' | 'diagnostics' | 'misc' | 'cmp' | 'dap' The category of the icons.
---@param spaces? boolean Adds a trailing space after the icon.
---@return table<string, string> set The icon set.
icons.get = function(category, spaces)
  spaces = spaces or false

  return spaces
      and setmetatable({}, {
        __index = function(self, key)
          return data[category][key] .. ' '
        end,
      })
    or data[category]
end

return icons
